services:
  authorization:
    build:
      context: ./authorization-api
    ports:
      - "8082:8082"

  notification:
    build:
      context: ./notification-api
    ports:
      - "8083:8083"

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: picpay-desafio-backend
